version: '3.9'

services:
  backend:
#    image: blockscout/blockscout:6.8.1.commit.1b1d3402
#    image: blockscout-backend-dev:local
#    image: harbor.devops.tantin.com/web/blockscout-backend:20250826
    image: harbor.devops.tantin.com/web/blockscout-backend:20250908
    working_dir: /app
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - BASE_CURRENCY=CTC
    env_file:
      - ../envs/common-blockscout.env
    volumes:
      - /data/tt-blockscout-backend/config/config_helper.exs:/app/releases/6.8.1/config_helper.exs
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"