version: '3.9'

services:
  backend:
#    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
#    image: blockscout/blockscout:6.8.1.commit.1b1d3402
    image: blockscout-backend-dev:local
    working_dir: /app
    #    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
#    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
#    command: sh -c "mix do deps.get, compile && mix phx.server"
#    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
#    command: sh -c "./blockscout/bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && ./blockscout/bin/blockscout start"
#    command: sh -c "mix do deps.get, compile && mix phx.server"
    command: sh -c "./bin/blockscout eval 'Elixir.Explorer.ReleaseTasks.create_and_migrate()' && ./bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
#      - /data/tt-blockscout-backend:/app:rw
      - /data/tt-blockscout-backend/docker-compose/services/config/config_helper.exs:/app/releases/6.8.1/config_helper.exs
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"