version: '3.9'

services:
  backend:
#    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
#    image: blockscout/blockscout:7.0.2
#    image: blockscout/blockscout:5.2.3.commit.f89f344e
#    image: blockscout/blockscout:6.8.1.commit.1b1d3402
    image: blockscout-backend-dev:local
    working_dir: /app
    #    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
#    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
#    command: sh -c "mix do deps.get, compile && mix phx.server"
    command: tail -f /dev/null
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-blockscout.env
    volumes:
      - ../blockscout:/app
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"